apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: tailscale-gateway
build:
  artifacts:
    - image: ghcr.io/infinity-blackhole/tailscale-gateway/controller
      ko:
        dependencies:
          paths:
            - cmd/controller
            - internal
            - go.mod
            - go.sum
        dir: ./cmd/controller
        fromImage: cgr.dev/chainguard/glibc-dynamic
profiles:
  - name: demo
    manifests:
      kustomize:
        paths:
          - manifests/demo
          - manifests/gateway/overlays/demo
