apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: tailscale-gateway
build:
  artifacts:
    - image: ghcr.io/shikanime-studio/tailscale-gateway/controller
      custom:
        buildCommand: nix shell nixpkgs#ko nixpkgs#skaffold --command ko build --platform linux/amd64,linux/arm64
manifests:
  kustomize:
    paths:
      - manifests/gateway
profiles:
  - name: demo
    manifests:
      kustomize:
        paths:
          - manifests/demo
