apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-gateway-controller
  namespace: tailscale-system
spec:
  template:
    spec:
      containers:
        - name: controller
          env:
            - name: TS_CERT_DOMAIN
              value: tail70d29d.ts.net
