apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: tailscale-gateway-demo
  labels:
    app.kubernetes.io/name: demo-app
    app.kubernetes.io/instance: demo
    app.kubernetes.io/part-of: tailscale-gateway-demo
    app.kubernetes.io/component: application
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    app.kubernetes.io/name: demo-app
    app.kubernetes.io/instance: demo
  ports:
    - port: 80
      targetPort: 80
