apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway.yaml
  - httproute.yaml
  - ns.yaml
  - svc.yaml
  - deploy.yaml
configMapGenerator:
  - name: demo
    namespace: tailscale-gateway-demo
    files:
      - demo/Caddyfile
  - name: demo-api-v1
    namespace: tailscale-gateway-demo
    files:
      - demo-api-v1/Caddyfile
  - name: demo-api-v2
    namespace: tailscale-gateway-demo
    files:
      - demo-api-v2/Caddyfile
