---
apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: tailscale-gateway-demo
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app.kubernetes.io/instance: demo
    app.kubernetes.io/name: demo
---
apiVersion: v1
kind: Service
metadata:
  name: demo-api
  namespace: tailscale-gateway-demo
  labels:
    app: demo-api
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: demo-api
