---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tailscale-gateway-controller
rules:
  - resources:
      - gateways
      - gateways/status
      - httproutes
      - httproutes/status
      - tcproutes
      - tcproutes/status
      - udproutes
      - udproutes/status
      - grpcroutes
      - grpcroutes/status
      - tlsroutes
      - tlsroutes/status
    apiGroups:
      - gateway.networking.k8s.io
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - resources:
      - ingresses
      - ingresses/status
    apiGroups:
      - networking.k8s.io
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - resources:
      - services
      - endpoints
      - secrets
      - configmaps
    apiGroups:
      - ""
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - resources:
      - serviceaccounts
    apiGroups:
      - ""
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - resources:
      - deployments
      - daemonsets
    apiGroups:
      - apps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - resources:
      - leases
    apiGroups:
      - coordination.k8s.io
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - resources:
      - events
    apiGroups:
      - ""
    verbs:
      - get
      - create
      - patch
  - resources:
      - clusterrolebindings
    apiGroups:
      - rbac.authorization.k8s.io
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - resources:
      - clusterroles
    apiGroups:
      - rbac.authorization.k8s.io
    resourceNames:
      - tailscale-gateway-proxy
    verbs:
      - bind
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tailscale-gateway-controller
roleRef:
  name: tailscale-gateway-controller
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
subjects:
  - name: tailscale-gateway-controller
    kind: ServiceAccount
    namespace: tailscale-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tailscale-gateway-proxy
rules:
  - resources:
      - secrets
    apiGroups:
      - ""
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - resources:
      - events
    apiGroups:
      - ""
    verbs:
      - get
      - create
      - patch
