jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - id: createGithubAppToken
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.OPERATOR_APP_ID }}
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ steps.createGithubAppToken.outputs.token }}
      - uses: shikanime-studio/setup-nix-action@v1
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token }}
      - uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - run:
          nix shell nixpkgs#ko nixpkgs#skaffold --command skaffold build --platform
          linux/amd64,linux/arm64
name: Build
"on":
  workflow_run:
    branches:
      - main
    types:
      - completed
    workflows:
      - check
