jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - id: createGithubAppToken
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.OPERATOR_APP_ID }}
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ steps.createGithubAppToken.outputs.token }}
      - uses: shikanime-studio/setup-nix-action@v1
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token }}
      - env:
          DOCKER_REGISTRY: ghcr.io
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.actor }}
        run:
          nix run nixpkgs#docker -- login "$DOCKER_REGISTRY" --username "$USERNAME"
          --password "$GITHUB_TOKEN"
      - run:
          nix shell nixpkgs#ko nixpkgs#skaffold --command skaffold build --platform
          linux/amd64,linux/arm64
  check:
    runs-on: ubuntu-latest
    steps:
      - id: createGithubAppToken
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.OPERATOR_APP_ID }}
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ steps.createGithubAppToken.outputs.token }}
      - uses: shikanime-studio/setup-nix-action@v1
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token }}
      - run: nix flake check --accept-flake-config --all-systems --no-pure-eval
name: Push
"on":
  push:
    branches:
      - main
      - release-*
